config/routes.rb
Rails.application.routes.draw do
  get 'game/start'

  get 'game/result'

  root 'top#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def start
    @document_title = "ゲーム開始"
  end

  def result
    @player_hand = params[:hand].to_i
    @computer_hand = rand(3)
    case @computer_hand - @player_hand
      when 0
        @result = 'aiko'
      when 1,-2
        @result = 'kachi'
      else
        @result = 'make'
    end

  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @document_title = "じゃんけんゲーム"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
  def image_of_hand(hand)
    image_tag(hand.to_s + '.gif')
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/game/result.html.erb
<%
@document_title = 'ゲーム結果'
%>
<p>あなたの手は</p>
<div>
  <%= image_of_hand(@player_hand) %>
</div>
<p>
  コンピュータの手は
</p>
<div>
  <%= image_of_hand(@computer_hand) %>
</div>
<p>
  <%=
    case @result
      when 'aiko'
      'アイコです'
      when 'kachi'
        '勝ちです'
      when 'make'
        '負けです'
    end
  %>
</p>
<p>
  <%= link_to 'トップページへ', root_path %><br>
  <%= link_to 'もう一度', :action => 'start' %>
</p>

app/views/game/start.html.erb
<%
  @document_title = 'ゲーム開始'
  hand_names = %w(gu choki pa)
  alt_texts = %w(ぐ　チョキ　パ)
%>
<p>あなたの手を選んでください。</p>
<div>
<% 0.upto(2) do |index| %>
  <%= link_to(image_tag(index.to_s+'.gif'), game_result_path(hand:index)) %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<html>
<head>
  <%= stylesheet_link_tag 'application' %>
  <meta http-equiv="content-type"
        content="text/html; charset=UTF-8"/>
  <title><%= h @document_title %></title>
</head>
<body>
<div class="header">
  じゃんけんゲーム
</div>
<div class="main">
  <%= yield %>
</div>
<div class="footer">
  Powered by Ruby on Rails
</div>
</body>
</html>

app/views/top/index.html.erb
<% @document_title = 'じゃんけんゲーム' %>
<p><%= link_to 'ゲーム開始', game_start_path %></p>